import { mkdir, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { join } from "node:path";
import type { GeneratedAdapter } from "./generate.js";

export interface ScaffoldAdapterOptions {
  root: string;
  generated: GeneratedAdapter;
  producerName: string;
  consumerName: string;
  maintainer?: string;
  author?: string;
  license?: string;
}

export interface ScaffoldAdapterResult {
  dir: string;
  manifestPath: string;
}

export async function scaffoldAdapter(opts: ScaffoldAdapterOptions): Promise<ScaffoldAdapterResult> {
  const dir = join(opts.root, opts.generated.adapterName);
  if (existsSync(dir)) throw new Error("already exists: " + dir);
  await mkdir(dir, { recursive: true });

  const manifest = {
    name: opts.generated.adapterName,
    version: "0.1.0",
    description: "Generated adapter: " + opts.producerName + " → " + opts.consumerName + ". " + opts.generated.rationale,
    kind: "adapter",
    language: "javascript",
    entrypoint: "index.js",
    inputSchema: "input.schema.json",
    outputSchema: "output.schema.json",
    dependencies: [],
    os: ["linux", "darwin"],
    permissions: [],
    risk: "low",
    trust: "community",
    provenance: {
      sourceRepo: "",
      sourceAuthor: opts.author ?? "SecStreet AI",
      license: opts.license ?? "MIT",
      version: "0.1.0",
      modifications: ["generated by " + opts.generated.provider + "/" + opts.generated.model],
    },
    maintainer: opts.maintainer ?? "SecStreet AI",
    execution: { timeoutMs: 15000 },
  };

  await writeFile(join(dir, "capability.json"), JSON.stringify(manifest, null, 2) + "\n");
  for (const [name, content] of Object.entries(opts.generated.files)) {
    await writeFile(join(dir, name), content);
  }

  return { dir, manifestPath: join(dir, "capability.json") };
}
